import type { Project } from './types';

const defaultPageStyle = {
  backgroundColor: '#ffffff',
  color: '#000000',
  fontFamily: 'sans-serif',
  display: 'flex',
  flexDirection: 'column',
  gap: '8px',
  padding: '16px',
};

export const demoProjects: Project[] = [
  {
    id: 'demo-calculator',
    name: 'Calculator App',
    description: 'A simple calculator using Drafter',
    lastModified: new Date().toISOString(),
    pages: [
      {
        id: 'calc-index',
        name: 'index',
        components: [
          { id: 'c1', kind: 'Header', content: 'Calculator', level: 1 },
          { id: 'c2', kind: 'TextBox', name: 'first_number', defaultValue: '' },
          { id: 'c3', kind: 'TextBox', name: 'second_number', defaultValue: '' },
          { id: 'c4', kind: 'Button', label: 'Calculate', routeId: 'r1' },
        ],
        componentStyles: {},
        pageStyle: { ...defaultPageStyle },
        ifAnnotations: [],
        forAnnotations: [],
        stateAnnotation: 'Show input form for calculator',
        position: { x: 100, y: 100 },
      },
      {
        id: 'calc-result',
        name: 'result',
        components: [
          { id: 'c5', kind: 'Header', content: 'Result', level: 1 },
          { id: 'c6', kind: 'Text', content: 'The result is:' },
          { id: 'c7', kind: 'Button', label: 'Calculate Again', routeId: 'r2' },
        ],
        componentStyles: {},
        pageStyle: { ...defaultPageStyle },
        ifAnnotations: [],
        forAnnotations: [{ id: 'f1', description: 'Show each entry', stateAttribute: 'history' }],
        stateAnnotation: 'Display calculation result and history',
        position: { x: 400, y: 100 },
      },
    ],
    routes: [
      {
        id: 'r1',
        sourcePageId: 'calc-index',
        targetPageId: 'calc-result',
        name: 'calculate',
        stateAnnotation: 'Perform the calculation and store result',
        ifAnnotations: [],
      },
      {
        id: 'r2',
        sourcePageId: 'calc-result',
        targetPageId: 'calc-index',
        name: 'back',
        stateAnnotation: 'Return to index page',
        ifAnnotations: [],
      },
    ],
    state: {
      id: 'calc-state',
      name: 'State',
      description: 'Calculator state',
      attributes: [
        { id: 'sa1', name: 'first_number', type: 'str', description: 'First operand', defaultValue: '""' },
        { id: 'sa2', name: 'second_number', type: 'str', description: 'Second operand', defaultValue: '""' },
        { id: 'sa3', name: 'result', type: 'str', description: 'Calculation result', defaultValue: '""' },
        { id: 'sa4', name: 'history', type: 'list[str]', description: 'History of calculations', defaultValue: '[]' },
      ],
    },
    secondaryDataclasses: [],
  },
  {
    id: 'demo-todo',
    name: 'Todo List App',
    description: 'A simple todo list using Drafter',
    lastModified: new Date().toISOString(),
    pages: [
      {
        id: 'todo-index',
        name: 'index',
        components: [
          { id: 't1', kind: 'Header', content: 'Todo List', level: 1 },
          { id: 't2', kind: 'TextBox', name: 'current_input', defaultValue: '' },
          { id: 't3', kind: 'Button', label: 'Add Todo', routeId: 'tr1' },
          { id: 't4', kind: 'SelectBox', name: 'filter', options: ['all', 'active', 'done'], defaultValue: 'all' },
        ],
        componentStyles: {},
        pageStyle: { ...defaultPageStyle },
        ifAnnotations: [],
        forAnnotations: [{ id: 'tf1', description: 'Show each todo item', stateAttribute: 'todos' }],
        stateAnnotation: 'Display todo list with filter',
        position: { x: 100, y: 100 },
      },
      {
        id: 'todo-add',
        name: 'add_todo',
        components: [
          { id: 't5', kind: 'Header', content: 'Add Todo', level: 2 },
          { id: 't6', kind: 'TextArea', name: 'current_input', defaultValue: '' },
          { id: 't7', kind: 'Button', label: 'Save', routeId: 'tr2' },
          { id: 't8', kind: 'Button', label: 'Cancel', routeId: 'tr3' },
        ],
        componentStyles: {},
        pageStyle: { ...defaultPageStyle },
        ifAnnotations: [],
        forAnnotations: [],
        stateAnnotation: 'Add a new todo item',
        position: { x: 400, y: 100 },
      },
    ],
    routes: [
      {
        id: 'tr1',
        sourcePageId: 'todo-index',
        targetPageId: 'todo-add',
        name: 'add_todo',
        stateAnnotation: 'Navigate to add todo form',
        ifAnnotations: [],
      },
      {
        id: 'tr2',
        sourcePageId: 'todo-add',
        targetPageId: 'todo-index',
        name: 'save_todo',
        stateAnnotation: 'Save the new todo and return to list',
        ifAnnotations: [],
      },
      {
        id: 'tr3',
        sourcePageId: 'todo-add',
        targetPageId: 'todo-index',
        name: 'cancel',
        stateAnnotation: 'Cancel and return to list',
        ifAnnotations: [],
      },
    ],
    state: {
      id: 'todo-state',
      name: 'State',
      description: 'Todo list state',
      attributes: [
        { id: 'ts1', name: 'todos', type: 'list[str]', description: 'List of todo items', defaultValue: '[]' },
        { id: 'ts2', name: 'current_input', type: 'str', description: 'Current text input', defaultValue: '""' },
        { id: 'ts3', name: 'filter', type: 'str', description: 'Current filter setting', defaultValue: '"all"' },
        { id: 'ts4', name: 'count', type: 'int', description: 'Total count of todos', defaultValue: '0' },
      ],
    },
    secondaryDataclasses: [],
  },
];
